### ISSUE TITLE
Is the comparison between different models fair?

### ISSUE THREAD

**Issue by AIR-hl** [sahsaeedi/TPO#3]
As stated in Appendix B, all models were trained under the same hyper-parm settings, `beta=0.1`， `global batc=16` etc. but differenct methods have different optim settings, such the best `beta` for DPO with `ultrafeedback`,`ultrachat`,`mistral-7b`, is `0.01`, just like it setted in `zephyr`. So is the results really comparable?

**Comment by sahsaeedi** [comment]
Hi,

Thank you for your question. In the first version of Zepyher, they reported Beta-0.1 as the best, and then in the new version of the model, they changed the hyperparameter; however, because the dataset we used is not ultra feedback-binarized (Refer to Experiments Section and Appendix B), the model fine-tuned with DPO may have different performance with Beta-0.01. For this reason, we used the best value reported in the DPO paper. In the new version of TPO, we used more data, and the discrepancy between DPO and TPO increased. We will update our paper ASAP.

**Comment by AIR-hl** [comment]
> Hi,
> 
> Thank you for your question. In the first version of Zepyher, they reported Beta-0.1 as the best, and then in the new version of the model, they changed the hyperparameter; however, because the dataset we used is not ultra feedback-binarized (Refer to Experiments Section and Appendix B), the model fine-tuned with DPO may have different performance with Beta-0.01. For this reason, we used the best value reported in the DPO paper. In the new version of TPO, we used more data, and the discrepancy between DPO and TPO increased. We will update our paper ASAP.

Thank you for your answer! : )
